services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"      # LocalStack main endpoint
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=apigateway,cloudformation,dynamodb,iam,lambda,s3
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
      - LAMBDA_EXECUTOR=docker
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_SESSION_TOKEN=test
      - LOCALSTACK_PUBLIC_URL=http://localhost:4566
      - PERSISTENCE=1
    volumes:
      - "./infra/localstack/init.sh:/etc/localstack/init/ready.d/init.sh"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "localstack-data:/var/lib/localstack"

volumes:
  localstack-data:
